Document: truecrack
Title: Debian truecrack Manual
Author: <insert document author here>
Abstract: This manual describes what truecrack is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/truecrack/truecrack.sgml.gz

Format: postscript
Files: /usr/share/doc/truecrack/truecrack.ps.gz

Format: text
Files: /usr/share/doc/truecrack/truecrack.text.gz

Format: HTML
Index: /usr/share/doc/truecrack/html/index.html
Files: /usr/share/doc/truecrack/html/*.html
